# Generated by Django 3.1.2 on 2021-01-28 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_is_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('Philosophy', 'Philosophy'), ('Fotography', 'Fotography'), ('Cinema', 'Cinema'), ('Literature', 'Literature'), ('Music', 'Music'), ('Poetry', 'Poetry'), ('Politics', 'Politics'), ('Economics', 'Economics'), ('Science', 'Science'), ('Sports', 'Sports'), ('Diversity', 'Diversity')], default='Diversity', max_length=20)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('update_date', models.DateTimeField(auto_now=True)),
                ('pub_date', models.DateField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
