# Generated by Django 3.1.2 on 2021-01-30 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210129_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='preview_text',
            field=models.CharField(default='Change this text before publishing', max_length=80),
        ),
    ]
