# Generated by Django 3.1.2 on 2021-01-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_article_preview_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='Title',
            field=models.TextField(default='Change this text before publishing', max_length=80),
        ),
        migrations.AlterField(
            model_name='article',
            name='preview_text',
            field=models.TextField(default='Change this text before publishing', max_length=300),
        ),
    ]
