# Generated by Django 3.1.2 on 2021-01-30 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210130_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='Title',
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Change this text before publishing', max_length=80),
        ),
    ]
