# Generated by Django 3.1.2 on 2021-02-03 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_article_lead_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_creator',
        ),
    ]
