# Generated by Django 3.1.6 on 2021-02-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_user_newsletter'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.BooleanField(default=True),
        ),
    ]
