# Generated by Django 3.1.6 on 2021-02-07 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_test'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
